In [1]:
import pandas as pd
import matplotlib.pyplot as plt
print("ready to go, all libs loaded")

ready to go, all libs loaded

In [10]:
url = "https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate"
tables = pd.read_html(url, storage_options={"User-Agent":"Mozilla/5.0"})
n= len(tables)
for i in range(n):
    print (tables[i])
df=tables[1]
print(df.columns)

    States and union territories of India ordered by
0  Area Population GDP (per capita) Abbreviations...
1                                                vte
                                             State/UT Census 2011[1]         \
                                             State/UT          Total   Male
0                                               India          74.04  82.14
1                     Andaman and Nicobar Islands[UT]          86.63  90.27
2                                      Andhra Pradesh          67.02  74.88
3                                   Arunachal Pradesh          65.38  72.55
4                                               Assam          72.19  77.85
5                                               Bihar          61.80  71.20
6                                        Chhattisgarh          70.28  80.27
7                                      Chandigarh[UT]          86.05  89.99
8                          Dadra and Nagar Haveli[UT]          76.34  85.17
9                                   Daman and Diu[UT]          87.10  91.54
10  Dadra and Nagar Haveli and Daman and Diu[UT][n...              -      -
11                                          Delhi[UT]          86.21  90.94
12                                                Goa          88.70  92.65
13                                            Gujarat          78.03  85.75
14                                            Haryana          75.55  84.06
15                                   Himachal Pradesh          82.80  89.53
16                      Jammu and Kashmir[UT][note 2]          67.16  76.75
17                                          Jharkhand          66.41  76.84
18                                          Karnataka          75.36  82.47
19                                             Kerala          94.00  96.11
20                                    Lakshadweep[UT]          91.85  95.56
21                                 Ladakh[UT][note 3]              -      -
22                                     Madhya Pradesh          69.32  78.73
23                                        Maharashtra          82.34  88.38
24                                            Manipur          76.94  83.58
25                                          Meghalaya          74.43  75.95
26                                            Mizoram          91.33  93.35
27                                           Nagaland          79.55  82.75
28                                             Odisha          72.87  81.59
29                                     Puducherry[UT]          85.85  91.26
30                                             Punjab          75.84  80.44
31                                          Rajasthan          66.11  79.19
32                                             Sikkim          81.42  86.55
33                                         Tamil Nadu          80.09  86.77
34                                  Telangana[note 4]              -      -
35                                            Tripura          87.22  92.53
36                                        Uttarakhand          78.82  87.40
37                                      Uttar Pradesh          67.68  77.28
38                                        West Bengal          76.36  81.69

          NSC survey (2017)[2][3]               PLFS report (2024)[4]        \
   Female                   Total   Male Female                 Total  Male
0   65.46                    77.7   84.7   70.3                  80.9  87.2
1   82.43                   86.27  90.11  81.84                  91.1  95.0
2   59.15                   67.40   80.0   59.5                  72.6  78.8
3   57.70                   66.95   73.4  59.50                  84.2  88.0
4   66.27                    85.9   90.1   81.2                  87.0  90.3
5   51.50                   69.70  84.91  73.91                  74.3  82.3
6   60.24                    77.3   85.4   68.8                  78.5  86.2
7   81.19                   86.43  90.54  81.38                  93.7  96.4
8   64.32                   77.65  86.46  77.65                     -     -
9   79.55                   87.07  91.48  87.07                     -     -
10      -                       -      -      -                  87.8  93.6
11  80.76                   88.70  82.40  93.70                  86.9  91.6
12  84.66                    87.4  92.81  81.84                  93.6  97.0
13  69.68                    82.4   89.5   74.8                  84.6  91.2
14  65.94                    80.4   88.0   71.3                  84.8  91.4
15  75.93                    86.6   92.9   80.5                  88.8  94.6
16  56.43                    77.3   85.7   68.0                  82.0  89.6
17  55.42                    74.3   83.0   64.7                  76.7  82.8
18  68.08                    77.2   83.4   70.5                  82.7  88.1
19  91.07                    96.2   97.4   95.2                  95.3  96.7
20  87.95                   92.28  96.11  88.25                  97.3  99.4
21      -                       -      -      -                  81.0  87.9
22  59.24                    73.7   81.2   65.5                  75.2  83.1
23  75.87                    84.8   90.7   78.4                  87.3  92.7
24  70.26                   79.85  86.49  73.17                  92.0  94.4
25  72.89                   75.48  77.17  73.78                  94.2  95.1
26  89.27                   99.01  93.72  89.40                  98.2  99.2
27  76.11                   80.11  83.29  80.11                  95.7  97.2
28  64.01                    77.3   84.0   70.3                  79.0  84.9
29  80.67                   86.55  92.12  86.55                  92.7  96.9
30  70.73                    83.7   88.5   78.5                  83.4  87.0
31  52.12                    69.7   80.8   57.6                  75.8  85.9
32  75.61                    82.2  87.29  76.43                  84.7  89.3
33  73.44                    82.9   87.9   77.9                  85.5  90.0
34      -                    72.8   80.5   65.1                  76.9  84.7
35  82.73                   87.75  92.18  83.15                  93.7  95.7
36  70.01                    87.6   94.3   80.7                  83.8  90.4
37  57.18                   73.00   81.8   63.4                  78.2  86.0
38  70.54                   80.50  84.80  76.10                  82.6  85.8


   Female
0    74.6
1    87.0
2    66.8
3    80.3
4    83.6
5    66.1
6    70.6
7    90.7
8       -
9       -
10   80.7
11   81.5
12   90.0
13   77.5
14   77.4
15   83.1
16   73.8
17   70.6
18   77.3
19   94.0
20   94.8
21   73.1
22   67.0
23   81.6
24   89.7
25   93.5
26   97.0
27   94.1
28   73.3
29   88.8
30   79.8
31   65.8
32   79.3
33   81.3
34   69.4
35   91.6
36   77.2
37   70.4
38   79.3
                       State/UT   1951   1961   1971   1981   1991   2001  \
0   Andaman and Nicobar Islands  30.30  40.07  51.15  63.19  73.02  81.30
1                Andhra Pradesh      -  21.19  24.57  35.66  44.08  60.47
2             Arunachal Pradesh      -   7.13  11.29  25.55  41.59  54.34
3                         Assam  18.53  32.95  33.94      -  52.89  63.25
4                         Bihar  13.49  21.95  23.17  32.32  37.49  47.00
5                    Chandigarh      -      -  70.43  74.80  77.81  81.94
6                  Chhattisgarh   9.41  18.14  24.08  32.63  42.91  64.66
7        Dadra and Nagar Haveli      -      -  18.13  32.90  40.71  57.63
8                 Daman and Diu      -      -      -      -  71.20  78.18
9                         Delhi      -  61.95  65.08  71.94  75.29  81.67
10                          Goa  23.48  35.41  51.96  65.71  75.51  82.01
11                      Gujarat  21.82  31.47  36.95  44.92  61.29  69.14
12                      Haryana      -      -  25.71  37.13  55.85  67.91
13             Himachal Pradesh      -      -      -      -  63.86  76.48
14            Jammu and Kashmir      -  12.95  21.71  30.64      -  55.52
15                    Jharkhand  12.93  21.14  23.87  35.03  41.39  53.56
16                    Karnataka      -  29.80  36.83  46.21  56.04  66.06
17                       Kerala  47.18  55.08  69.75  78.85  89.81  90.86
18                  Lakshadweep  15.23  27.15  51.76  68.42  81.78  86.66
19               Madhya Pradesh  13.16  21.41  27.27  38.63  44.67  63.74
20                  Maharashtra  27.91  35.08  45.77  57.24  64.87  76.84
21                      Manipur  12.57  36.04  38.47  49.66  59.89  70.50
22                    Meghalaya      -  26.92  29.49  42.05  49.10  62.56
23                      Mizoram  31.14  44.01  53.80  59.88  82.26  88.80
24                     Nagaland  10.52  21.95  33.78  50.28  61.65  66.59
25                       Odisha  15.80  21.66  26.18  33.62  49.09  63.08
26                   Puducherry      -  43.65  53.38  65.14  74.74  81.24
27                       Punjab      -      -  34.12  43.37  58.51  69.65
28                    Rajasthan    8.5  18.12  22.57  30.11  38.55  60.41
29                       Sikkim      -      -  17.74  34.05  56.94  68.81
30                   Tamil Nadu      -  36.39  45.40  54.39  62.66  73.45
31                      Tripura      -  20.24  30.98  50.10  60.44  73.19
32                Uttar Pradesh  12.02  20.87  23.99  32.65  40.71  56.27
33                  Uttarakhand  18.93  18.05  33.26  46.06  57.75  71.62
34                  West Bengal  24.61  34.46  38.86  48.65  57.70  68.64
35                        India  18.33  28.30  34.45  43.57  52.21  64.84

     2011
0   86.63
1   67.02
2   65.38
3   72.19
4   61.80
5   86.05
6   70.28
7   76.24
8   87.10
9   86.21
10  88.70
11  78.03
12  75.55
13  82.80
14  67.16
15  66.41
16  75.36
17  94.00
18  91.85
19  69.32
20  82.34
21  76.94
22  74.43
23  91.33
24  79.55
25  72.87
26  85.85
27  75.84
28  66.11
29  81.42
30  80.33
31  87.22
32  67.68
33  78.82
34  76.26
35  74.04
           Social Group Rural        Urban        Total
           Social Group  Male Female  Male Female  Male Female
0       Scheduled Tribe  75.6   58.8  91.3   79.6  77.5   61.3
1       Scheduled Caste  78.0   60.9  88.4   75.3  80.3   63.9
2  Other Backward Class  81.7   64.2  91.1   80.5  84.4   68.9
3                Others  87.6   74.5  95.0   88.6  90.8   80.6
4                 India  81.5   65.0  92.2   82.8  84.7   70.3
    Religion NSO 2018[6]                                  PLFS 2024[7]        \
    Religion       Rural        Urban        Total               Rural
    Religion        Male Female  Male Female  Male Female        Total  Male
0      Hindu        81.8   64.5  93.4   83.8  85.1   70.0         77.3  84.7
1     Muslim        77.4   64.8  85.8   75.6  80.6   68.8         77.1  83.5
2  Christian        84.4   77.0  95.5   91.4  88.2   82.2         85.8  88.0
3       Sikh        92.7   96.4  94.2   95.3  88.9   90.1         80.9  84.3
4      India        81.5   65.0  92.2   82.8  84.7   70.3         77.5  84.7


         Urban              Total
  Female Total  Male Female Total  Male Female
0   69.8  89.7  93.7   85.4  80.8  87.3   74.2
1   70.9  83.7  87.6   79.6  79.5  85.0   74.0
2   83.6  94.5  95.9   93.2  88.9  90.8   87.1
3   77.3  90.9  94.7   87.1  83.4  86.9   79.8
4   70.4  88.9  92.9   84.9  80.9  87.2   74.6
MultiIndex([(               'State/UT', 'State/UT'),
            (         'Census 2011[1]',    'Total'),
            (         'Census 2011[1]',     'Male'),
            (         'Census 2011[1]',   'Female'),
            ('NSC survey (2017)[2][3]',    'Total'),
            ('NSC survey (2017)[2][3]',     'Male'),
            ('NSC survey (2017)[2][3]',   'Female'),
            (  'PLFS report (2024)[4]',    'Total'),
            (  'PLFS report (2024)[4]',     'Male'),
            (  'PLFS report (2024)[4]',   'Female')],
           )

In [8]:
df= tables[1]
df_clean=df.loc[:,[("State/UT", "State/UT"),("PLFS report (2024)[4]","Total")]]
df_clean.columns= ["State","LiteracyRates"]
df_clean

                                                State LiteracyRates
0                                               India          80.9
1                     Andaman and Nicobar Islands[UT]          91.1
2                                      Andhra Pradesh          72.6
3                                   Arunachal Pradesh          84.2
4                                               Assam          87.0
5                                               Bihar          74.3
6                                        Chhattisgarh          78.5
7                                      Chandigarh[UT]          93.7
8                          Dadra and Nagar Haveli[UT]             -
9                                   Daman and Diu[UT]             -
10  Dadra and Nagar Haveli and Daman and Diu[UT][n...          87.8
11                                          Delhi[UT]          86.9
12                                                Goa          93.6
13                                            Gujarat          84.6
14                                            Haryana          84.8
15                                   Himachal Pradesh          88.8
16                      Jammu and Kashmir[UT][note 2]          82.0
17                                          Jharkhand          76.7
18                                          Karnataka          82.7
19                                             Kerala          95.3
20                                    Lakshadweep[UT]          97.3
21                                 Ladakh[UT][note 3]          81.0
22                                     Madhya Pradesh          75.2
23                                        Maharashtra          87.3
24                                            Manipur          92.0
25                                          Meghalaya          94.2
26                                            Mizoram          98.2
27                                           Nagaland          95.7
28                                             Odisha          79.0
29                                     Puducherry[UT]          92.7
30                                             Punjab          83.4
31                                          Rajasthan          75.8
32                                             Sikkim          84.7
33                                         Tamil Nadu          85.5
34                                  Telangana[note 4]          76.9
35                                            Tripura          93.7
36                                        Uttarakhand          83.8
37                                      Uttar Pradesh          78.2
38                                        West Bengal          82.6

In [11]:
print("yaayyayaya dataClean successfull")

yaayyayaya dataClean successfull

In [15]:
df_clean["State"] = df_clean["State"].str.replace(r"\[.*?\]", "", regex=True)
df_clean["State"] = df_clean["State"].str.strip()
df_clean["LiteracyRates"] = pd.to_numeric(df_clean["LiteracyRates"], errors="coerce")
df_clean = df_clean.reset_index(drop=True)
df_clean

                                       State  LiteracyRates
0                                      India           80.9
1                Andaman and Nicobar Islands           91.1
2                             Andhra Pradesh           72.6
3                          Arunachal Pradesh           84.2
4                                      Assam           87.0
5                                      Bihar           74.3
6                               Chhattisgarh           78.5
7                                 Chandigarh           93.7
8                     Dadra and Nagar Haveli            NaN
9                              Daman and Diu            NaN
10  Dadra and Nagar Haveli and Daman and Diu           87.8
11                                     Delhi           86.9
12                                       Goa           93.6
13                                   Gujarat           84.6
14                                   Haryana           84.8
15                          Himachal Pradesh           88.8
16                         Jammu and Kashmir           82.0
17                                 Jharkhand           76.7
18                                 Karnataka           82.7
19                                    Kerala           95.3
20                               Lakshadweep           97.3
21                                    Ladakh           81.0
22                            Madhya Pradesh           75.2
23                               Maharashtra           87.3
24                                   Manipur           92.0
25                                 Meghalaya           94.2
26                                   Mizoram           98.2
27                                  Nagaland           95.7
28                                    Odisha           79.0
29                                Puducherry           92.7
30                                    Punjab           83.4
31                                 Rajasthan           75.8
32                                    Sikkim           84.7
33                                Tamil Nadu           85.5
34                                 Telangana           76.9
35                                   Tripura           93.7
36                               Uttarakhand           83.8
37                             Uttar Pradesh           78.2
38                               West Bengal           82.6

In [16]:
df_clean.to_csv("plfs_literacy_2024_clean.csv", index=False)