In [2]:
import pandas as pd
import matplotlib.pyplot as plt

# Cleaning the Data
## PRS data political represntation of women 2023

In [3]:
prs_tables_df  = pd.read_csv("data/prs_women_participation.csv", header=None, names=['States','Women_pct'])
prs_tables_df.head()

           States  Women_pct
0  Andhra Pradesh          9
1       Arunachal          7
2           Assam          5
3           Bihar         12
4    Chhattisgarh         18

In [16]:
prs_tables_df.to_csv("prs_political_participation.csv", index=False)

## Workforce participation of men and women 2019 - plfs
The data mainly uses the workforce participation of women between ages of 15 and 29 years

In [4]:
workforce_tables_df = pd.read_csv("data/workforce.csv")
workforce_tables_df.head()

,_id,id,year,quarter,state_name,age_group,gender,value,state_code
0,138,137,2019,April-June,All-India,15-29 Years,Female,16.3,99
1,23,22,2019,April-June,All-India,15-29 Years,Male,58.4,99
2,116,115,2019,April-June,Andhra Pradesh,15-29 Years,Female,20.3,28
3,1,0,2019,April-June,Andhra Pradesh,15-29 Years,Male,54.0,28
4,2,1,2019,April-June,Assam,15-29 Years,Male,52.3,18

In [5]:
workforce_tables_df = workforce_tables_df.loc[: , ['state_name','gender','value']]
workforce_tables_df.head()

       state_name  gender  value
0       All-India  Female   16.3
1       All-India    Male   58.4
2  Andhra Pradesh  Female   20.3
3  Andhra Pradesh    Male   54.0
4           Assam    Male   52.3

In [11]:
females_workforce_df= workforce_tables_df[workforce_tables_df['gender'] == 'Female']
females_workforce_df=females_workforce_df.rename(columns={'value':'female_points'})
females_workforce_df.head()

       state_name  gender  female_points
0       All-India  Female           16.3
2  Andhra Pradesh  Female           20.3
5           Assam  Female           13.4
6           Bihar  Female            3.2
9    Chhattisgarh  Female           18.3

In [12]:
males_workforce_df= workforce_tables_df[workforce_tables_df['gender'] == 'Male']
males_workforce_df=males_workforce_df.rename(columns={'value':'male_points'})
males_workforce_df.head()

       state_name gender  male_points
1       All-India   Male         58.4
3  Andhra Pradesh   Male         54.0
4           Assam   Male         52.3
7           Bihar   Male         45.2
8    Chhattisgarh   Male         59.1

In [15]:
workforce_tables_df= pd.merge(females_workforce_df, males_workforce_df, on='state_name')
workforce_tables_df=workforce_tables_df.loc[:,['state_name','female_points','male_points']]
workforce_tables_df.head()

       state_name  female_points  male_points
0       All-India           16.3         58.4
1  Andhra Pradesh           20.3         54.0
2           Assam           13.4         52.3
3           Bihar            3.2         45.2
4    Chhattisgarh           18.3         59.1

In [19]:
workforce_tables_df.to_csv('workforce_difference_women_and_men.csv',index=False)

## TUS 2019 data for unpaid labour

In [22]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [23]:
tus_df= pd.read_excel("data/tus.xlsx")
tus_df.head(20)

,Statement 6.1: Minutes spent in a day on an average per participant in the activities of major divisions of TUS activity classification irrespective of whether it is a major activity or not (considering all the activities in a time slot),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Statement 6.1: Minutes spent in a day on an average per participant in the activities of major divisions of TUS activity classification irrespective of whether it is a major activity or not (considering all the activities in a time slot).1
0,Andhra Pradesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,major divisions of TUS activity classification,male,NaN,NaN,female,NaN,NaN,person,NaN,NaN,NaN
2,NaN,15-29 years,15-59 years,6 years and above,15-29 years,15-59 years,6 years and above,15-29 years,15-59 years,6 years and above,NaN
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),NaN
4,rural,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Employment and related activities,424,441,431,312,343,335,392,407,397,NaN
6,Production of goods for own final use,82,113,109,61,66,65,68,82,81,NaN
7,Unpaid domestic services for household members,74,81,85,243,256,245,217,226,216,NaN
8,Unpaid caregiving services for household members,71,70,71,160,133,130,142,113,111,NaN
9,"Unpaid volunteer, trainee and other unpaid work",172,154,151,138,109,104,159,134,131,NaN
10,Learning,431,415,442,426,415,444,429,415,443,NaN
11,"Socializing and communication, community parti...",167,167,166,122,131,136,145,149,151,NaN
12,"Culture, leisure, mass-media and sports practices",188,165,180,183,176,185,185,171,183,NaN
13,Self-care and maintenance,703,700,721,696,690,713,699,695,717,NaN
14,estimated persons (00),34726,93256,130489,36928,99451,134918,71709,192835,265562,NaN
15,sample persons,1273,3394,4747,1349,3615,4860,2624,7013,9612,NaN
16,urban,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Employment and related activities,499,504,496,374,372,366,466,466,459,NaN
18,Production of goods for own final use,46,76,74,50,49,49,49,54,54,NaN
19,Unpaid domestic services for household members,72,76,79,238,259,250,209,228,219,NaN

This data is really messed up the better solution is manually sorting data